# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 1024mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - ./db/prov-init.sql:/docker-entrypoint-initdb.d/init.sql
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: wf-obs
    ports:
      - "5432:5432"  


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

