# Use postgres/example user/password credentials

services:

  api:
    image: wf-obs-api
    build: ./api
    depends_on:
      db:
        condition: service_started
    networks:
      - gw-repo-network
    environment:
      DATABASE_URL: postgresql://postgres:example@db/wf-obs
    ports:
      - "80:80"
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 1024mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - ./db/prov-init.sql:/docker-entrypoint-initdb.d/init.sql
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: wf-obs
    ports:
      - "5432:5432"  
    networks:
      - gw-repo-network

networks:
  gw-repo-network:

