
plugins {
    id 'io.nextflow.nextflow-plugin' version '1.0.0-beta.12'
}

version = project.file('VERSION').text.trim()

nextflowPlugin {
    nextflowVersion = '25.10.0'

    provider = 'gwrepo'
    className = 'nextflow.gwrepo.GwRepoPlugin'
    extensionPoints = [
        'nextflow.gwrepo.GwRepoConfig',
        'nextflow.gwrepo.GwRepoObserverFactory'
    ]
}
